include <../../globals/ObtGlobalConst.scad>

// Bar dimensions
OBT_BAR_WIDTH = OBT_GLOBAL_BAR_WIDTH;
OBT_BAR_INNER_WIDTH = 5.4;
OBT_BAR_HEIGHT = OBT_GLOBAL_BAR_HEIGHT;
OBT_BAR_HOLE_DIAMETER = OBT_GLOBAL_HOLE_DIAMETER;
OBT_BAR_HOLE_DIAMETER_OUTER = 6.7;
OBT_BAR_HOLE_DISTANCE = OBT_GLOBAL_HOLE_DISTANCE;

