include <../../globals/ObtGlobalConst.scad>

// Connector dimenstions
OBT_CON_WIDTH = OBT_GLOBAL_BAR_WIDTH;
OBT_BAR_INNER_WIDTH = OBT_GLOBAL_BAR_INNER_WIDTH;
OBT_CON_HEIGHT = OBT_GLOBAL_BAR_HEIGHT;
OBT_CON_HOLE_DISTANCE = OBT_GLOBAL_HOLE_DISTANCE;

OBT_CON_HOLE_DIAMETER = OBT_GLOBAL_HOLE_DIAMETER;
OBT_CON_HOLE_DIAMETER_OUTER = OBT_GLOBAL_HOLE_DIAMETER_OUTER;

