include <../../globals/ObtGlobalConst.scad>

// Pin dimensions
OBT_PIN_DIAMETER_OUTER = OBT_GLOBAL_HOLE_CHAMFER_DIAMETER - 0.5;
OBT_PIN_DIAMETER_INNER = OBT_GLOBAL_HOLE_DIAMETER - 0.2;
OBT_PIN_DIAMETER_HOLE = 3.4;
OBT_PIN_LENGTH_2 = 15.5;
